package test.dynamic.datasource.model;

public class DbTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_test.db
     *
     * @mbg.generated
     */
    private String db;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_test.id
     *
     * @return the value of db_test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_test.id
     *
     * @param id the value for db_test.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_test.db
     *
     * @return the value of db_test.db
     *
     * @mbg.generated
     */
    public String getDb() {
        return db;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_test.db
     *
     * @param db the value for db_test.db
     *
     * @mbg.generated
     */
    public void setDb(String db) {
        this.db = db == null ? null : db.trim();
    }
}